### ISSUE TITLE
无法保存.pcd和.g2o文件

### ISSUE THREAD

**Issue by HuaYuXiao** [Yixin-F/better_fastlio2#16]
```yaml
common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    camera_topic: "/camera/color/image_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

    rootDir: "/home/easonhua/easondrone_ws/src/slam/better_fastlio2/data_lio/"
    savePCD: true                         # https://github.com/TixiaoShan/LIO-SAM/issues/3
    savePCDDirectory: "PCDs/"        
    saveSCD: true 
    saveSCDDirectory: "SCDs/"
    saveLOG: true
    saveLOGDirectory: "LOG/"
    map_save_en: true  # global map
    pcd_save_interval: -1                 # how many LiDAR frames saved in each pcd
```

![Image](https://github.com/user-attachments/assets/6dc48a62-e6e6-49da-a5da-9e9a099b74f3)
